/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucionesDigitalesRouteImport } from './routes/soluciones-digitales'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as LpRouteImport } from './routes/lp'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const SolucionesDigitalesRoute = SolucionesDigitalesRouteImport.update({
  id: '/soluciones-digitales',
  path: '/soluciones-digitales',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/lp': typeof LpRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-digitales': typeof SolucionesDigitalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/lp': typeof LpRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-digitales': typeof SolucionesDigitalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/lp': typeof LpRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-digitales': typeof SolucionesDigitalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/lp' | '/servicios' | '/soluciones-digitales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/lp' | '/servicios' | '/soluciones-digitales'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/lp'
    | '/servicios'
    | '/soluciones-digitales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  LpRoute: typeof LpRoute
  ServiciosRoute: typeof ServiciosRoute
  SolucionesDigitalesRoute: typeof SolucionesDigitalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soluciones-digitales': {
      id: '/soluciones-digitales'
      path: '/soluciones-digitales'
      fullPath: '/soluciones-digitales'
      preLoaderRoute: typeof SolucionesDigitalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  LpRoute: LpRoute,
  ServiciosRoute: ServiciosRoute,
  SolucionesDigitalesRoute: SolucionesDigitalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
